#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

getVersion() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    curl --silent $PROXY "https://api.github.com/repos/MediaBrowser/Emby/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
}

VERSION=$(getVersion)
echo "Emby version: $VERSION"
URL="https://github.com/MediaBrowser/Emby.Releases/releases/download/${VERSION}/emby-server-deb_${VERSION}_amd64.deb"
SRC="/usr/local/src"

dl $URL $SRC

mv $SRC/*.deb $SRC/emby-server.deb

