#!/bin/sh -ex

apt install emby-server -y

service emby-server start &  EMBY_PID=$!

# Delay until emby has finished starting
EMBY_SERVER=127.0.0.1
EMBY_PORT=8096
CURL="curl --output /dev/null --silent --head --fail"
until $($CURL http://$EMBY_SERVER:$EMBY_PORT); do
    sleep 5
done

# Rename the file server for WebDAVCGI
CONF=/var/www/webdavcgi/webdav.conf
sed -i "s|FILESERVER|MEDIASERVER|" $CONF

# Rename the samba service
CONF=/etc/samba/smb.conf
sed -i "s|FILESERVER|MEDIASERVER|" $CONF
sed -i "s|FileServer|MediaServer|" $CONF

# Change default group to users
usermod -g users emby
chgrp -R users /var/lib/emby-server
chgrp -R users /var/lib/emby-server/*

# Change group assigned to emby
CONF=/etc/emby-server.conf
echo "EMBY_GROUP=\"users\"" >> $CONF

# Make restart script installed by emby executable
#chmod +x /var/lib/emby-server/restart.sh

#Setup default media folders
mkdir -p /srv/storage/Music
chown emby:users /srv/storage/Music
chmod g+w /srv/storage/Music

mkdir -p /srv/storage/Movies
chown emby:users /srv/storage/Movies
chmod g+w /srv/storage/Movies

mkdir -p /srv/storage/TVShows
chown emby:users /srv/storage/TVShows
chmod g+w /srv/storage/TVShows

mkdir -p /srv/storage/Photos
chown emby:users /srv/storage/Photos
chmod g+w /srv/storage/Photos

# Replace text in README
CONF=/srv/storage/README.txt
sed -i "s|File Server|Media Server|" $CONF

# Stop the service
service emby-server stop

sleep 30

adduser emby sudo

# Remove Emby data directory (Necessary for emby to run properly in final appliance, Regenerated when emby first starts)
rm -r /var/lib/emby-server

# add TurnKey credit to log in page
mkdir -p /var/lib/emby-server/config/
mv /usr/local/src/emby-branding.xml  /var/lib/emby-server/config/branding.xml

# Apache config for WebDavCGI
a2dissite 000-default.conf 
a2ensite webdavcgi.conf 
a2ensite tkl-webcp.conf
