#!/bin/bash -e
# setup Emby media server

. /etc/default/inithooks

EMBY_SERVER=127.0.0.1
EMBY_PORT=8096
CURL="curl --output /dev/null --silent --head --fail"

chown -R emby:users /var/lib/emby
systemctl enable emby-server@emby.service

# Start Emby server
service emby-server start

# Delay until emby has finished starting
until $($CURL http://$EMBY_SERVER:$EMBY_PORT); do
    echo -n .
    sleep 5
done

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/emby-server.py --pass="$APP_PASS"

if [ "$APP_PASS" != "" ]; then
    echo $APP_PASS > /etc/embypass
else
    rm -f /etc/embypass
fi

service emby-server stop

# https on Emby requires PKCS #12 certificate
mkdir /etc/ssl/emby
SSL_PASSWORD=$(mcookie)
CERT_PATH=/etc/ssl/emby/cert.pfx
openssl pkcs12 -export -out $CERT_PATH -inkey /etc/ssl/private/cert.key -in /etc/ssl/private/cert.pem -password pass:$SSL_PASSWORD
chmod +r $CERT_PATH
EMBY_CONFIG=/var/lib/emby/config/system.xml
sed -i '/<CertificatePath*/d' $EMBY_CONFIG
sed -i '/<CertificatePassword*/d' $EMBY_CONFIG
sed -i "/<\/ServerConfiguration/i \ <CertificatePath>$CERT_PATH</CertificatePath>\n <CertificatePassword>$SSL_PASSWORD</CertificatePassword>" $EMBY_CONFIG

# Restart Emby
service emby-server stop
service emby-server start
