## Reverse proxy the media server to 12322
<VirtualHost *:12322>
        ServerName localhost
        SSLEngine On

        <Proxy *>
                Require all granted
        </Proxy>

        SetEnv proxy-nokeepalive 1
        SetEnv proxy-sendchunked 1

        ProxyRequests     Off
        ProxyPreserveHost On

        Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"

        ProxyPass /socket ws://127.0.0.1:8096/socket
        ProxyPassReverse /socket ws://127.0.0.1:8096/socket
        ProxyPass / http://127.0.0.1:8096/
        ProxyPassReverse / http://127.0.0.1:8096/
</VirtualHost>
